### ISSUE TITLE
#question Traduzione italiana già esistente

### ISSUE THREAD

**Issue by alebaffa** [neonsoftware/go-tour-it#1]
Ciao, ho appena trovato questo repository e volevo dirti che ho tradotto anche io il Go Tour in Italiano. La mia traduzione è già completa e deployata su http://go-tour-ita.appspot.com/. Ho già comunicato in [mailing-list ufficiale](https://groups.google.com/forum/#!topic/golang-nuts/-yr-iCbP1Gw) e ho anche già inviato la [modifica](https://groups.google.com/forum/#!topic/golang-codereviews/VnAUy5HRU1s) nel sorgente principale del Go Tour per includere il link alla mia traduzione.
Mi spiace tanto di non aver trovato questo progetto prima, avrei potuto continuare dal tuo anziché cominciare da zero.

Puoi dargli un'occhiata, se ti va, e darmi un tuo feedback.

Ciao,
Alessandro

**Comment by neonsoftware** [comment]
Ciao Alessandro, 

Già, mi spiace non aver pubblicato meglio. 
Io avevo postato nel gruppo riguardo al dominio già usato ma era finita nel nulla, aspettando non avevo poi ancora continuato. 

Da qui poi l'importante è che Go abbia istruzioni in Italiano, graze per il tuo lavoro !

**Comment by neonsoftware** [comment]
Quando ci saranno modifiche da aggiornare non esitare a farmi sapere se hai bisogno di collaborazione. 

Ciao !
